apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplewebapp-deployment
  labels:
    app: samplewebapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: samplewebapp
  template:
    metadata:
      labels:
        app: samplewebapp
    spec:
      containers:
        - name: samplewebapp
          image: gregkolodny/samplewebapp
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: samplewebapp-service
spec:
  type: NodePort
  selector:
    app: samplewebapp
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
